#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ruby-progressbar
Version  : 1.7.5
Release  : 3
URL      : https://rubygems.org/downloads/ruby-progressbar-1.7.5.gem
Source0  : https://rubygems.org/downloads/ruby-progressbar-1.7.5.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks

%description
Ruby/ProgressBar
================================
[![Build Status](https://secure.travis-ci.org/jfelchner/ruby-progressbar.png?branch=master)](http://travis-ci.org/jfelchner/ruby-progressbar) [![Code Climate](https://codeclimate.com/github/jfelchner/ruby-progressbar.png)](https://codeclimate.com/github/jfelchner/ruby-progressbar) [![Code Climate](https://codeclimate.com/github/jfelchner/ruby-progressbar/coverage.png)](https://codeclimate.com/github/jfelchner/ruby-progressbar)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ruby-progressbar-1.7.5
gem spec %{SOURCE0} -l --ruby > rubygem-ruby-progressbar.gemspec

%build
gem build rubygem-ruby-progressbar.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ruby-progressbar-1.7.5.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.2.0/cache/ruby-progressbar-1.7.5.gem
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/autofinish-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/autostart-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/bar-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/cdesc-Base.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/decrement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/finish-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/finished%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/finished-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/format%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/increment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/inspect-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/output-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/pause-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/paused%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/percentage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/progress%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/progress_mark%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/progressable-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/rate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/remainder_mark%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/resume-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/started%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/stopped%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/timer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/title%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/title-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/title_comp-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/total%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Base/update_progress-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/calculate_length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/cdesc-Length.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/current_length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/dynamic_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/dynamic_width_stty-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/dynamic_width_tput-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/length_changed%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/length_override%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/length_override-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/reset_length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/terminal_width-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/Length/unix%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/RunningAverage/calculate-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/RunningAverage/cdesc-RunningAverage.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Calculators/cdesc-Calculators.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/bar-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/bar_with_percentage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/cdesc-Bar.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/complete_bar-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/completed_length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/incomplete_space-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/incomplete_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/integrated_percentage_complete_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/progress-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/progress_mark-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/remainder_mark-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/standard_complete_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/to_s-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/unknown_progress_frame-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/unknown_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Bar/upa_steps-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Percentage/cdesc-Percentage.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Percentage/justified_percentage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Percentage/justified_percentage_with_precision-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Percentage/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Percentage/percentage-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Percentage/percentage_with_precision-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Percentage/progress-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Rate/base_rate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Rate/cdesc-Rate.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Rate/elapsed_seconds-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Rate/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Rate/progress-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Rate/rate_of_change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Rate/rate_of_change_with_precision-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Rate/rate_scale-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Rate/scaled_rate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Rate/started_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Rate/stopped_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Rate/timer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/cdesc-Time.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/elapsed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/elapsed_with_label-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/estimated-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/estimated_seconds_remaining-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/estimated_with_elapsed_fallback-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/estimated_with_friendly_oob-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/estimated_with_label-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/estimated_with_no_oob-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/estimated_with_unknown_oob-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/out_of_bounds_time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/out_of_bounds_time_format%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/out_of_bounds_time_format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/progress-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Time/timer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Title/cdesc-Title.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Title/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/Title/title-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Components/cdesc-Components.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/Formatter/cdesc-Formatter.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/Formatter/process-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/Molecule/bar_molecule%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/Molecule/cdesc-Molecule.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/Molecule/full_key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/Molecule/key-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/Molecule/lookup_value-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/Molecule/method_name-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/Molecule/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/Molecule/non_bar_molecule%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/String/bar_molecule_placeholder_length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/String/bar_molecules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/String/cdesc-String.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/String/displayable_length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/String/molecules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/String/non_bar_molecules-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Format/cdesc-Format.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/InvalidProgressError/cdesc-InvalidProgressError.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/bar-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/cdesc-Output.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/clear_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/detect-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/length_calculator-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/log-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/print_and_flush-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/refresh-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/stream-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/throttle-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Output/with_refresh-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/NonTty/bar_update_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/NonTty/cdesc-NonTty.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/NonTty/clear-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/NonTty/default_format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/NonTty/eol-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/NonTty/last_update_length-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/NonTty/refresh_with_format_change-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/NonTty/resolve_format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/Tty/bar_update_string-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/Tty/cdesc-Tty.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/Tty/clear-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/Tty/default_format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/Tty/eol-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/Tty/resolve_format-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Outputs/cdesc-Outputs.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/absolute-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/cdesc-Progress.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/decrement-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/finish-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/finished%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/increment-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/none%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/percentage_completed-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/percentage_completed_with_precision-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/progress%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/progress-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/running_average-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/smoothing-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/starting_position-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/total%3d-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/total-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Progress/unknown%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Throttle/cdesc-Throttle.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Throttle/choke-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Throttle/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Throttle/rate-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Throttle/started_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Throttle/stopped_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Throttle/timer-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Time/cdesc-Time.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Time/now-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Time/time_mocking_library_methods-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Time/unmocked_time_method-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/cdesc-Timer.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/divide_seconds-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/elapsed_seconds-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/elapsed_whole_seconds-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/new-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/pause-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/reset%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/reset-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/restart-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/resume-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/start-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/started%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/started_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/stop-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/stopped%3f-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/stopped_at-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/Timer/time-i.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/cdesc-ProgressBar.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/ProgressBar/create-c.ri
/usr/lib64/ruby/gems/2.2.0/doc/ruby-progressbar-1.7.5/ri/cache.ri
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/LICENSE
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/README.md
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/Rakefile
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/base.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/calculators/length.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/calculators/length_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/calculators/running_average.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/components.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/components/bar.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/components/percentage.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/components/rate.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/components/time.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/components/title.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/errors/invalid_progress_error.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/format.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/format/formatter.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/format/molecule.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/format/string.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/output.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/outputs/non_tty.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/outputs/tty.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/progress.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/throttle.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/time.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/timer.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/lib/ruby-progressbar/version.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/fixtures/benchmark.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/base_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/calculators/running_average_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/components/bar_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/components/percentage_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/components/rate_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/components/throttle_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/components/time_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/components/title_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/format/formatter_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/format/molecule_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/format/string_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/output_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/outputs/non_tty_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/outputs/tty_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/progress_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/time_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/ruby-progressbar/timer_spec.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.2.0/gems/ruby-progressbar-1.7.5/spec/support/time.rb
/usr/lib64/ruby/gems/2.2.0/specifications/ruby-progressbar-1.7.5.gemspec
