#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-ruby-progressbar
Version  : 1.8.1
Release  : 6
URL      : https://rubygems.org/downloads/ruby-progressbar-1.8.1.gem
Source0  : https://rubygems.org/downloads/ruby-progressbar-1.8.1.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
BuildRequires : ruby
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rubygems-tasks

%description
Ruby/ProgressBar
================================
[![Gem Version](https://img.shields.io/gem/v/ruby-progressbar.svg)](https://rubygems.org/gems/ruby-progressbar) ![Rubygems Rank Overall](https://img.shields.io/gem/rt/ruby-progressbar.svg) ![Rubygems Rank Daily](https://img.shields.io/gem/rd/ruby-progressbar.svg) ![Rubygems Downloads](https://img.shields.io/gem/dv/ruby-progressbar/stable.svg) [![Build Status](https://img.shields.io/travis/jfelchner/ruby-progressbar/master.svg)](http://travis-ci.org/jfelchner/ruby-progressbar) [![Code Climate](https://codeclimate.com/github/jfelchner/ruby-progressbar.svg)](https://codeclimate.com/github/jfelchner/ruby-progressbar) [![Code Climate](https://codeclimate.com/github/jfelchner/ruby-progressbar/coverage.svg)](https://codeclimate.com/github/jfelchner/ruby-progressbar)

%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n ruby-progressbar-1.8.1
gem spec %{SOURCE0} -l --ruby > rubygem-ruby-progressbar.gemspec

%build
gem build rubygem-ruby-progressbar.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
ruby-progressbar-1.8.1.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/ruby-progressbar-1.8.1.gem
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/LICENSE.txt
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/README.md
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/Rakefile
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/base.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/calculators/length.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/calculators/length_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/calculators/running_average.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/components.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/components/bar.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/components/percentage.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/components/rate.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/components/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/components/title.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/errors/invalid_progress_error.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/format.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/format/formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/format/molecule.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/format/string.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/output.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/outputs/non_tty.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/outputs/tty.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/progress.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/throttle.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/time.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/timer.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/lib/ruby-progressbar/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/fixtures/benchmark.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/base_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/calculators/length_calculator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/calculators/running_average_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/components/bar_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/components/percentage_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/components/rate_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/components/throttle_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/components/time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/components/title_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/format/formatter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/format/molecule_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/format/string_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/output_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/outputs/non_tty_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/outputs/tty_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/progress_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/time_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/ruby-progressbar/timer_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/ruby-progressbar-1.8.1/spec/support/time.rb
/usr/lib64/ruby/gems/2.3.0/specifications/ruby-progressbar-1.8.1.gemspec
